const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: "ACCOUNT_FETCH_AUTHENTICATED_SUCCESS"
};

const ACCOUNT_INFO = {
  FETCH: "ACCOUNT_FETCH_INFO",
  FETCH_ERROR: "ACCOUNT_FETCH_INFO_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_INFO_SUCCESS"
};

export { ACCOUNT, ACCOUNT_INFO };
