const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS: "ACCOUNT_FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: "ACCOUNT_FETCH_AUTHENTICATED_SUCCESS",
  FETCH_DELETE_SUCCESS: "ACCOUNT_FETCH_DELETE_SUCCESS"
};

const BOOKMARK = {
  FETCH: "BOOKMARK_FETCH_INFO",
  FETCH_ERROR: "BOOKMARK_FETCH_INFO_ERROR",
  FETCH_SUCCESS: "BOOKMARK_FETCH_INFO_SUCCESS",
  FETCH_DELETE_SUCCESS: "BOOKMARK_FETCH_DELETE_SUCCESS"
};

const ACCOUNT_BOOKMARKS = {
  FETCH: "ACCOUNT_FETCH_BOOKMARKS",
  FETCH_ERROR: "ACCOUNT_FETCH_BOOKMARKS_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_BOOKMARKS_SUCCESS"
};

const ACCOUNT_INFO = {
  FETCH: "ACCOUNT_FETCH_INFO",
  FETCH_ERROR: "ACCOUNT_FETCH_INFO_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_INFO_SUCCESS"
};

export { ACCOUNT, BOOKMARK, ACCOUNT_BOOKMARKS, ACCOUNT_INFO };
